name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Installer les dépendances
        run: pip install pytest

      - name: Exécuter les tests
        run: python -m unittest test_app.py
      - name: Analyse du code avec SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=aghiles76
            -Dsonar.projectKey=aghiles76_tp-ci-cd
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher le déploiement sur Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d5dradm3jp1c73f2ajbg?key=_8zTJT24hJw"
